### ISSUE TITLE
Subentry sharing

### ISSUE THREAD

**Issue by TejaGo** [elexis-eu/lexonomy#35] opened 2019-02-14 13:21 UTC
A dictionary administrator will be able to configure a dictionary such that some parts of an entry will be 'shareable' between several entries. This will ensure that, for example, phraseological subentries are able to appear under more than one headword.

Note: This will implement a suggestion from my Raslan paper http://www.lexiconista.com/raslan2016.pdf

**Comment by michmech** [comment] 2019-02-25 08:49
Done (this feature was launched at Euralex 2018, see [this paper](http://www.lexiconista.com/euralex2018.pdf)) but needs a bit more work to tie some loose ends (for example the titling of subentries and their alphabetical sorting), so I'm leaving this open and assigned to myself.

**Comment by eftomi** [comment] 2019-11-01 19:23
Hi Michal, should this functionality on https://www.lexonomy.eu/ already be present? When adding subentry as in Fig 7 of Euralex 2018 paper nothing happens when clicking on Insert button (the editor window closes however the subentry doesn't get added). Also, the settings option under <phraseme> as in Fig 3 doesn't show. I tried with various browsers.

Thanks,
Tomaz

**Comment by michmech** [comment] 2019-11-02 11:15
> Hi Michal, should this functionality on https://www.lexonomy.eu/ already be present?

Yes, it should (and is).

> When adding subentry as in Fig 7 of Euralex 2018 paper nothing happens when clicking on Insert button (the editor window closes however the subentry doesn't get added).

That seems like a bug. Can you give me (valselob@gmail.com) access to the dictionary where this happens? I'll have a look there.

> Also, the settings option under as in Fig 3 doesn't show. I tried with various browsers.

Ah, this is not a bug. I assumed there would be a settings option when I was writing the paper but in the end it turned out we didn't need one. The screenshot is telling a small lie. :-)

**Comment by magbb** [comment] 2020-03-30 22:10
> That seems like a bug. Can you give me ([valselob@gmail.com](mailto:valselob@gmail.com)) access to the dictionary where this happens? I'll have a look there.

I am affected by this bug as well, insertion of subentries does not work using the dialog box. The box closes without anything happening, in the JS console I get "Uncaught TypeError: Cannot read property 'documentElement' of undefined". Were you able to reproduce it?

**Comment by magbb** [comment] 2020-03-31 08:48
I think I found the solution, at least it works in my case:

Line 213 in lexonomy.py reads:

total, entries = ops.listEntries(dictDB, dictID, configs, request.query.doctype, request.query.lemma, "wordstart", 100, False, True)

It should probably be:

total, entries = ops.listEntries(dictDB, dictID, configs, request.query.doctype, request.query.lemma, "wordstart", 100, False, True, fullXML=True)

When requesting the full XML, insertion works as expected. Am I right?

**Closed** 2022-02-24 13:40 UTC
Labels: entry structure, difficulty-medium, question?
