### ISSUE TITLE
allow reordering of dictionary list

### ISSUE THREAD

**Issue by mjakubicek** [elexis-eu/lexonomy#98] opened 2019-04-12 19:09 UTC
For the case of having a lot of dictionaries on the front screen, it would be good to be able to reorder the list. Possible, mutually non-exclusive, options, entail:
- being able to arbitrarily reorder the list
- being able to mark a dictionary as favourite which would bring it to the top
- being able to archive the dictionary would would bring it to the bottom or to a separate view

This includes the problem of unwanted shares.

**Comment by rambousek** [comment] 2022-02-23 14:01
duplicate of several issues #212 #213 #215

**Closed by rambousek** 2022-02-23 14:01 UTC
Labels: good for beginners, difficulty-simple, ELEXIS-technical
